<?php

declare(strict_types=1);

namespace Stewart\Codegen\Emitter;

use Nette\PhpGenerator\PhpNamespace;
use Nette\PhpGenerator\PsrPrinter;

final class GeneratedCodePrinter extends PsrPrinter
{
    public const string MARKER = '@generated by `stewart generate`';

    public bool $singleParameterOnOneLine = true;

    public static function buildHeaderComment(): string
    {
        return \sprintf("/**\n * %s.\n *\n * Do not edit: run `make generate` instead.\n */", self::MARKER);
    }

    public static function isGenerated(string $contents): bool
    {
        return str_contains($contents, self::MARKER);
    }

    public function printGenerated(PhpNamespace $namespace): string
    {
        // Printed by hand: nette puts the file comment above `declare`; this repository puts it below.
        return "<?php\n\ndeclare(strict_types=1);\n\n"
            . self::buildHeaderComment() . "\n\n"
            . $this->printNamespace($namespace);
    }
}
