<?php

declare(strict_types=1);

namespace Stewart\Codegen\Attribute;

final readonly class AttributeCatalog
{
    private const array COMMON = [
        'assumed_state' => AttributeKind::Bool,
        'attribution' => AttributeKind::String,
        'device_class' => AttributeKind::String,
        'entity_picture' => AttributeKind::String,
        'icon' => AttributeKind::String,
        'state_class' => AttributeKind::String,
        'supported_features' => AttributeKind::Float,
        'unit_of_measurement' => AttributeKind::String,
    ];

    private const array BY_DOMAIN = [
        'alarm_control_panel' => [
            'changed_by' => AttributeKind::String,
            'code_arm_required' => AttributeKind::Bool,
            'code_format' => AttributeKind::String,
        ],
        'automation' => [
            'current' => AttributeKind::Float,
            'id' => AttributeKind::String,
            'last_triggered' => AttributeKind::String,
            'max' => AttributeKind::Float,
            'mode' => AttributeKind::String,
        ],
        'calendar' => [
            'all_day' => AttributeKind::Bool,
            'description' => AttributeKind::String,
            'end_time' => AttributeKind::String,
            'location' => AttributeKind::String,
            'message' => AttributeKind::String,
            'start_time' => AttributeKind::String,
        ],
        'camera' => [
            'access_token' => AttributeKind::String,
            'frontend_stream_type' => AttributeKind::String,
        ],
        'climate' => [
            'current_humidity' => AttributeKind::Float,
            'current_temperature' => AttributeKind::Float,
            'fan_mode' => AttributeKind::String,
            'fan_modes' => AttributeKind::Array,
            'humidity' => AttributeKind::Float,
            'hvac_action' => AttributeKind::String,
            'hvac_modes' => AttributeKind::Array,
            'max_humidity' => AttributeKind::Float,
            'max_temp' => AttributeKind::Float,
            'min_humidity' => AttributeKind::Float,
            'min_temp' => AttributeKind::Float,
            'preset_mode' => AttributeKind::String,
            'preset_modes' => AttributeKind::Array,
            'swing_horizontal_mode' => AttributeKind::String,
            'swing_horizontal_modes' => AttributeKind::Array,
            'swing_mode' => AttributeKind::String,
            'swing_modes' => AttributeKind::Array,
            'target_temp_high' => AttributeKind::Float,
            'target_temp_low' => AttributeKind::Float,
            'target_temp_step' => AttributeKind::Float,
            'temperature' => AttributeKind::Float,
        ],
        'counter' => [
            'editable' => AttributeKind::Bool,
            'initial' => AttributeKind::Float,
            'maximum' => AttributeKind::Float,
            'minimum' => AttributeKind::Float,
            'step' => AttributeKind::Float,
        ],
        'cover' => [
            'current_position' => AttributeKind::Float,
            'current_tilt_position' => AttributeKind::Float,
        ],
        'device_tracker' => [
            'altitude' => AttributeKind::Float,
            'battery_level' => AttributeKind::Float,
            'gps_accuracy' => AttributeKind::Float,
            'host_name' => AttributeKind::String,
            'ip' => AttributeKind::String,
            'latitude' => AttributeKind::Float,
            'longitude' => AttributeKind::Float,
            'mac' => AttributeKind::String,
            'source_type' => AttributeKind::String,
        ],
        'event' => [
            'event_type' => AttributeKind::String,
            'event_types' => AttributeKind::Array,
        ],
        'fan' => [
            'direction' => AttributeKind::String,
            'oscillating' => AttributeKind::Bool,
            'percentage' => AttributeKind::Float,
            'percentage_step' => AttributeKind::Float,
            'preset_mode' => AttributeKind::String,
            'preset_modes' => AttributeKind::Array,
        ],
        'humidifier' => [
            'action' => AttributeKind::String,
            'available_modes' => AttributeKind::Array,
            'current_humidity' => AttributeKind::Float,
            'humidity' => AttributeKind::Float,
            'max_humidity' => AttributeKind::Float,
            'min_humidity' => AttributeKind::Float,
            'mode' => AttributeKind::String,
        ],
        'image' => [
            'access_token' => AttributeKind::String,
        ],
        'input_boolean' => [
            'editable' => AttributeKind::Bool,
        ],
        'input_button' => [
            'editable' => AttributeKind::Bool,
        ],
        'input_datetime' => [
            'day' => AttributeKind::Float,
            'editable' => AttributeKind::Bool,
            'has_date' => AttributeKind::Bool,
            'has_time' => AttributeKind::Bool,
            'hour' => AttributeKind::Float,
            'minute' => AttributeKind::Float,
            'month' => AttributeKind::Float,
            'second' => AttributeKind::Float,
            'timestamp' => AttributeKind::Float,
            'year' => AttributeKind::Float,
        ],
        'input_number' => [
            'editable' => AttributeKind::Bool,
            'initial' => AttributeKind::Float,
            'max' => AttributeKind::Float,
            'min' => AttributeKind::Float,
            'mode' => AttributeKind::String,
            'step' => AttributeKind::Float,
        ],
        'input_select' => [
            'editable' => AttributeKind::Bool,
            'options' => AttributeKind::Array,
        ],
        'input_text' => [
            'editable' => AttributeKind::Bool,
            'max' => AttributeKind::Float,
            'min' => AttributeKind::Float,
            'mode' => AttributeKind::String,
            'pattern' => AttributeKind::String,
        ],
        'light' => [
            'brightness' => AttributeKind::Float,
            'color_mode' => AttributeKind::String,
            'color_temp_kelvin' => AttributeKind::Float,
            'effect' => AttributeKind::String,
            'effect_list' => AttributeKind::Array,
            'hs_color' => AttributeKind::Array,
            'max_color_temp_kelvin' => AttributeKind::Float,
            'min_color_temp_kelvin' => AttributeKind::Float,
            'rgb_color' => AttributeKind::Array,
            'rgbw_color' => AttributeKind::Array,
            'rgbww_color' => AttributeKind::Array,
            'supported_color_modes' => AttributeKind::Array,
            'xy_color' => AttributeKind::Array,
        ],
        'lock' => [
            'changed_by' => AttributeKind::String,
            'code_format' => AttributeKind::String,
        ],
        'media_player' => [
            'app_id' => AttributeKind::String,
            'app_name' => AttributeKind::String,
            'entity_picture' => AttributeKind::String,
            'group_members' => AttributeKind::Array,
            'is_volume_muted' => AttributeKind::Bool,
            'media_album_artist' => AttributeKind::String,
            'media_album_name' => AttributeKind::String,
            'media_artist' => AttributeKind::String,
            'media_channel' => AttributeKind::String,
            'media_content_id' => AttributeKind::String,
            'media_content_type' => AttributeKind::String,
            'media_duration' => AttributeKind::Float,
            'media_episode' => AttributeKind::String,
            'media_playlist' => AttributeKind::String,
            'media_position' => AttributeKind::Float,
            'media_position_updated_at' => AttributeKind::String,
            'media_season' => AttributeKind::String,
            'media_series_title' => AttributeKind::String,
            'media_title' => AttributeKind::String,
            'media_track' => AttributeKind::Float,
            'repeat' => AttributeKind::String,
            'shuffle' => AttributeKind::Bool,
            'sound_mode' => AttributeKind::String,
            'sound_mode_list' => AttributeKind::Array,
            'source' => AttributeKind::String,
            'source_list' => AttributeKind::Array,
            'volume_level' => AttributeKind::Float,
        ],
        'number' => [
            'max' => AttributeKind::Float,
            'min' => AttributeKind::Float,
            'mode' => AttributeKind::String,
            'step' => AttributeKind::Float,
        ],
        'person' => [
            'device_trackers' => AttributeKind::Array,
            'gps_accuracy' => AttributeKind::Float,
            'id' => AttributeKind::String,
            'latitude' => AttributeKind::Float,
            'longitude' => AttributeKind::Float,
            'source' => AttributeKind::String,
            'user_id' => AttributeKind::String,
        ],
        'remote' => [
            'activity_list' => AttributeKind::Array,
            'current_activity' => AttributeKind::String,
        ],
        'scene' => [
            'entity_id' => AttributeKind::Array,
            'id' => AttributeKind::String,
        ],
        'script' => [
            'current' => AttributeKind::Float,
            'last_triggered' => AttributeKind::String,
            'max' => AttributeKind::Float,
            'mode' => AttributeKind::String,
        ],
        'select' => [
            'options' => AttributeKind::Array,
        ],
        'sensor' => [
            'last_reset' => AttributeKind::String,
            'options' => AttributeKind::Array,
        ],
        'siren' => [
            'available_tones' => AttributeKind::Array,
        ],
        'sun' => [
            'azimuth' => AttributeKind::Float,
            'elevation' => AttributeKind::Float,
            'next_dawn' => AttributeKind::String,
            'next_dusk' => AttributeKind::String,
            'next_midnight' => AttributeKind::String,
            'next_noon' => AttributeKind::String,
            'next_rising' => AttributeKind::String,
            'next_setting' => AttributeKind::String,
            'rising' => AttributeKind::Bool,
        ],
        'text' => [
            'max' => AttributeKind::Float,
            'min' => AttributeKind::Float,
            'mode' => AttributeKind::String,
            'pattern' => AttributeKind::String,
        ],
        'timer' => [
            'duration' => AttributeKind::String,
            'editable' => AttributeKind::Bool,
            'finishes_at' => AttributeKind::String,
            'remaining' => AttributeKind::String,
            'restore' => AttributeKind::Bool,
        ],
        'update' => [
            'auto_update' => AttributeKind::Bool,
            'display_precision' => AttributeKind::Float,
            'in_progress' => AttributeKind::Bool,
            'installed_version' => AttributeKind::String,
            'latest_version' => AttributeKind::String,
            'release_summary' => AttributeKind::String,
            'release_url' => AttributeKind::String,
            'skipped_version' => AttributeKind::String,
            'title' => AttributeKind::String,
            'update_percentage' => AttributeKind::Float,
        ],
        'vacuum' => [
            'battery_icon' => AttributeKind::String,
            'battery_level' => AttributeKind::Float,
            'fan_speed' => AttributeKind::String,
            'fan_speed_list' => AttributeKind::Array,
            'status' => AttributeKind::String,
        ],
        'valve' => [
            'current_position' => AttributeKind::Float,
        ],
        'water_heater' => [
            'away_mode' => AttributeKind::String,
            'current_temperature' => AttributeKind::Float,
            'max_temp' => AttributeKind::Float,
            'min_temp' => AttributeKind::Float,
            'operation_list' => AttributeKind::Array,
            'operation_mode' => AttributeKind::String,
            'target_temp_high' => AttributeKind::Float,
            'target_temp_low' => AttributeKind::Float,
            'temperature' => AttributeKind::Float,
        ],
        'weather' => [
            'apparent_temperature' => AttributeKind::Float,
            'cloud_coverage' => AttributeKind::Float,
            'dew_point' => AttributeKind::Float,
            'humidity' => AttributeKind::Float,
            'ozone' => AttributeKind::Float,
            'precipitation_unit' => AttributeKind::String,
            'pressure' => AttributeKind::Float,
            'pressure_unit' => AttributeKind::String,
            'temperature' => AttributeKind::Float,
            'temperature_unit' => AttributeKind::String,
            'uv_index' => AttributeKind::Float,
            'visibility' => AttributeKind::Float,
            'visibility_unit' => AttributeKind::String,
            'wind_bearing' => AttributeKind::Mixed,
            'wind_gust_speed' => AttributeKind::Float,
            'wind_speed' => AttributeKind::Float,
            'wind_speed_unit' => AttributeKind::String,
        ],
        'zone' => [
            'editable' => AttributeKind::Bool,
            'latitude' => AttributeKind::Float,
            'longitude' => AttributeKind::Float,
            'passive' => AttributeKind::Bool,
            'persons' => AttributeKind::Array,
            'radius' => AttributeKind::Float,
        ],
    ];

    /** @return array<string, AttributeKind> */
    public function listKindsForDomain(string $domain): array
    {
        return self::BY_DOMAIN[$domain] ?? [];
    }

    public function findKind(string $domain, string $key): ?AttributeKind
    {
        return self::BY_DOMAIN[$domain][$key] ?? self::COMMON[$key] ?? null;
    }
}
