{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "stewart.fullname" . }}
  labels:
    {{- include "stewart.labels" . | nindent 4 }}
data:
  stewart.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
{{- end }}
