<?php

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace PHPSTORM_META;

registerArgumentsSet('stewart_binary_sensor_entity_ids', 'binary_sensor.hall_motion');
expectedArguments(\Stewart\Codegen\Tests\Fixtures\Expected\BinarySensorEntities::getEntity(), 0, argumentsSet('stewart_binary_sensor_entity_ids'));
registerArgumentsSet('stewart_input_number_entity_ids', 'input_number.target_temperature');
expectedArguments(\Stewart\Codegen\Tests\Fixtures\Expected\InputNumberEntities::getEntity(), 0, argumentsSet('stewart_input_number_entity_ids'));
registerArgumentsSet('stewart_light_entity_ids', 'light.1st_floor', 'light.hall', 'light.porch2', 'light.porch_2');
expectedArguments(\Stewart\Codegen\Tests\Fixtures\Expected\LightEntities::getEntity(), 0, argumentsSet('stewart_light_entity_ids'));
registerArgumentsSet('stewart_sensor_entity_ids', 'sensor.broken_probe', 'sensor.hall_humidity', 'sensor.hall_temperature');
expectedArguments(\Stewart\Codegen\Tests\Fixtures\Expected\SensorEntities::getEntity(), 0, argumentsSet('stewart_sensor_entity_ids'));
registerArgumentsSet('stewart_switch_entity_ids', 'switch.pump');
expectedArguments(\Stewart\Codegen\Tests\Fixtures\Expected\SwitchEntities::getEntity(), 0, argumentsSet('stewart_switch_entity_ids'));
registerArgumentsSet('stewart_area_ids', 'hall', 'kitchen');
expectedArguments(\Stewart\Contracts\Registry\EntityFilter::inArea(), 0, argumentsSet('stewart_area_ids'));
expectedArguments(\Stewart\Contracts\Registry\EntityFilter::withArea(), 0, argumentsSet('stewart_area_ids'));
expectedArguments(\Stewart\Contracts\Registry\Registry::findArea(), 0, argumentsSet('stewart_area_ids'));
expectedArguments(\Stewart\Contracts\Registry\Registry::listDevicesInArea(), 0, argumentsSet('stewart_area_ids'));
expectedArguments(\Stewart\Contracts\Service\ServiceTarget::forAreas(), 0, argumentsSet('stewart_area_ids'));
expectedArguments(\Stewart\Contracts\Registry\AreaId::__construct(), 0, argumentsSet('stewart_area_ids'));
registerArgumentsSet('stewart_floor_ids', 'ground');
expectedArguments(\Stewart\Contracts\Registry\EntityFilter::onFloor(), 0, argumentsSet('stewart_floor_ids'));
expectedArguments(\Stewart\Contracts\Registry\EntityFilter::withFloor(), 0, argumentsSet('stewart_floor_ids'));
expectedArguments(\Stewart\Contracts\Registry\Registry::findFloor(), 0, argumentsSet('stewart_floor_ids'));
expectedArguments(\Stewart\Contracts\Registry\Registry::listAreasOnFloor(), 0, argumentsSet('stewart_floor_ids'));
expectedArguments(\Stewart\Contracts\Service\ServiceTarget::forFloors(), 0, argumentsSet('stewart_floor_ids'));
expectedArguments(\Stewart\Contracts\Registry\FloorId::__construct(), 0, argumentsSet('stewart_floor_ids'));
registerArgumentsSet('stewart_label_ids', 'night');
expectedArguments(\Stewart\Contracts\Registry\EntityFilter::labelled(), 0, argumentsSet('stewart_label_ids'));
expectedArguments(\Stewart\Contracts\Registry\EntityFilter::withLabel(), 0, argumentsSet('stewart_label_ids'));
expectedArguments(\Stewart\Contracts\Registry\Registry::findLabel(), 0, argumentsSet('stewart_label_ids'));
expectedArguments(\Stewart\Contracts\Service\ServiceTarget::forLabels(), 0, argumentsSet('stewart_label_ids'));
expectedArguments(\Stewart\Contracts\Registry\LabelId::__construct(), 0, argumentsSet('stewart_label_ids'));
