<?php

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace PHPSTORM_META;

registerArgumentsSet('stewart_binary_sensor_entity_ids', 'binary_sensor.hall_motion');
expectedArguments(\Stewart\Codegen\Tests\Fixtures\Expected\BinarySensorEntities::getEntity(), 0, argumentsSet('stewart_binary_sensor_entity_ids'));
registerArgumentsSet('stewart_input_number_entity_ids', 'input_number.target_temperature');
expectedArguments(\Stewart\Codegen\Tests\Fixtures\Expected\InputNumberEntities::getEntity(), 0, argumentsSet('stewart_input_number_entity_ids'));
registerArgumentsSet('stewart_light_entity_ids', 'light.1st_floor', 'light.hall', 'light.porch2', 'light.porch_2');
expectedArguments(\Stewart\Codegen\Tests\Fixtures\Expected\LightEntities::getEntity(), 0, argumentsSet('stewart_light_entity_ids'));
registerArgumentsSet('stewart_sensor_entity_ids', 'sensor.broken_probe', 'sensor.hall_humidity', 'sensor.hall_temperature');
expectedArguments(\Stewart\Codegen\Tests\Fixtures\Expected\SensorEntities::getEntity(), 0, argumentsSet('stewart_sensor_entity_ids'));
registerArgumentsSet('stewart_switch_entity_ids', 'switch.pump');
expectedArguments(\Stewart\Codegen\Tests\Fixtures\Expected\SwitchEntities::getEntity(), 0, argumentsSet('stewart_switch_entity_ids'));
