<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\Entity\Entity;
use Stewart\Contracts\Entity\EntityId;
use Stewart\Contracts\Exception\StateException;
use Stewart\Contracts\HaContext;
use Stewart\Contracts\Service\ServiceTarget;
use Stewart\Contracts\Service\ServiceTargetSource;
use Stewart\Contracts\StateChangeStream;

/**
 * One `binary_sensor` entity.
 */
final readonly class BinarySensorEntity implements ServiceTargetSource
{
    private Entity $entity;

    public function __construct(
        HaContext $ha,
        public EntityId $id,
    ) {
        $this->entity = $ha->getEntity($id);
    }

    public function getState(): ?BinarySensorState
    {
        return BinarySensorState::fromNullableState($this->entity->getState());
    }

    /**
     * @throws StateException
     */
    public function requireState(): BinarySensorState
    {
        return new BinarySensorState($this->entity->requireState());
    }

    public function watchStateChanges(): StateChangeStream
    {
        return $this->entity->watchStateChanges();
    }

    /**
     * @return array<string, mixed>
     */
    public function listAttributes(): array
    {
        $state = $this->entity->getState();

        return $state === null ? [] : $state->attributes;
    }

    public function getEntity(): Entity
    {
        return $this->entity;
    }

    public function toServiceTarget(): ServiceTarget
    {
        return $this->entity->toServiceTarget();
    }
}
