<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\Entity\EntityId;
use Stewart\Contracts\HaContext;

/**
 * The `binary_sensor` entities.
 */
final class BinarySensorEntities
{
    /** Hall Motion */
    public BinarySensorEntity $hallMotion {
        get => new BinarySensorEntity($this->ha, new EntityId('binary_sensor.hall_motion'));
    }

    public function __construct(private readonly HaContext $ha)
    {
    }
}
