<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\HaContext;

/**
 * Every entity Home Assistant knows, by domain.
 */
final class Entities
{
    /** Entities in the `binary_sensor` domain. */
    public BinarySensorEntities $binarySensor {
        get => new BinarySensorEntities($this->ha);
    }

    /** Entities in the `input_number` domain. */
    public InputNumberEntities $inputNumber {
        get => new InputNumberEntities($this->ha);
    }

    /** Entities in the `light` domain. */
    public LightEntities $light {
        get => new LightEntities($this->ha);
    }

    /** Entities in the `sensor` domain. */
    public SensorEntities $sensor {
        get => new SensorEntities($this->ha);
    }

    /** Entities in the `switch` domain. */
    public SwitchEntities $switch {
        get => new SwitchEntities($this->ha);
    }

    public function __construct(private readonly HaContext $ha)
    {
    }
}
