<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\HaContext;
use Stewart\Contracts\Service\ServiceTargetSource;

/**
 * The `homeassistant` services.
 */
final readonly class HomeassistantServices
{
    public function __construct(private HaContext $ha)
    {
    }

    /**
     * Set location
     *
     * Updates the Home Assistant location.
     *
     * @param int|float $latitude Latitude. Latitude of your location. -90 to 90
     * @param int|float $longitude Longitude. Longitude of your location. -180 to 180
     * @param int|float|null $elevation Elevation. Elevation of your location above sea level
     */
    public function setLocation(int|float $latitude, int|float $longitude, int|float|null $elevation = null): void
    {
        $this->ha->callService('homeassistant', 'set_location', [
            'latitude' => $latitude,
            'longitude' => $longitude,
            'elevation' => $elevation,
        ]);
    }

    /**
     * Generic turn on
     *
     * Generic service to turn devices on under any domain.
     */
    public function turnOn(ServiceTargetSource $target): void
    {
        $this->ha->callService('homeassistant', 'turn_on', [], $target);
    }
}
