<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\State\EntityState;

/**
 * What a `input_number` entity is doing.
 */
final readonly class InputNumberState
{
    public string $value;

    public function __construct(public EntityState $raw)
    {
        $this->value = $raw->state;
    }

    public static function fromNullableState(?EntityState $raw): ?self
    {
        return $raw === null ? null : new self($raw);
    }

    public function getStateAsFloat(): ?float
    {
        return $this->raw->getStateAsFloat();
    }

    public function isUnavailable(): bool
    {
        return $this->raw->isUnavailable();
    }

    public function getFriendlyName(): string
    {
        return $this->raw->getFriendlyName();
    }

    public function getEditable(): ?bool
    {
        return $this->raw->getBoolAttribute('editable');
    }

    public function getInitial(): ?float
    {
        return $this->raw->getFloatAttribute('initial');
    }

    public function getMax(): ?float
    {
        return $this->raw->getFloatAttribute('max');
    }

    public function getMin(): ?float
    {
        return $this->raw->getFloatAttribute('min');
    }

    public function getMode(): ?string
    {
        return $this->raw->getStringAttribute('mode');
    }

    public function getStep(): ?float
    {
        return $this->raw->getFloatAttribute('step');
    }
}
