<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\Entity\EntityId;
use Stewart\Contracts\HaContext;

/**
 * The `input_number` entities.
 */
final class InputNumberEntities
{
    /** Target Temperature */
    public InputNumberEntity $targetTemperature {
        get => new InputNumberEntity($this->ha, new EntityId('input_number.target_temperature'));
    }

    public function __construct(private readonly HaContext $ha)
    {
    }
}
