<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\HaContext;
use Stewart\Contracts\Service\ServiceTargetSource;
use Stewart\Contracts\State\EventContext;

/**
 * The `light` services.
 */
final readonly class LightServices
{
    public function __construct(private HaContext $ha)
    {
    }

    /**
     * Set state
     *
     * Writes a state straight onto a light, bypassing its integration.
     *
     * @param string|int|float $value Value. The state to write
     */
    public function state(ServiceTargetSource $target, string|int|float $value): EventContext
    {
        return $this->ha->callService('light', 'state', [
            'value' => $value,
        ], $target);
    }

    /**
     * Turn off
     *
     * Turns off one or more lights.
     *
     * @param int|float|null $transition Transition. Duration it takes to get to the next state. 0 to 300 seconds
     */
    public function turnOff(ServiceTargetSource $target, int|float|null $transition = null): EventContext
    {
        return $this->ha->callService('light', 'turn_off', [
            'transition' => $transition,
        ], $target);
    }

    /**
     * Turn on
     *
     * Turns on one or more lights and adjusts their properties, even when they are on already.
     *
     * @param int|float|null $brightnessPct Brightness. Percentage of full brightness. 0 to 100 %
     * @param int|float|null $colorTempKelvin Color temperature. Colour temperature in Kelvin. 2000 to 6500
     * @param string|int|float|null $effect Effect. Light effect
     * @param 'long'|'short'|null $flash Flash. Tell the light to flash
     * @param mixed $profile Profile. A light profile, if the integration offers any
     * @param array{int, int, int}|null $rgbColor RGB color. The color in RGB format
     * @param int|float|null $transition Transition. Duration it takes to get to the next state. 0 to 300 seconds
     * @param true|null $white White. Set the light to white mode
     */
    public function turnOn(
        ServiceTargetSource $target,
        int|float|null $brightnessPct = null,
        int|float|null $colorTempKelvin = null,
        string|int|float|null $effect = null,
        ?string $flash = null,
        mixed $profile = null,
        ?array $rgbColor = null,
        int|float|null $transition = null,
        ?bool $white = null,
    ): EventContext {
        return $this->ha->callService('light', 'turn_on', [
            'brightness_pct' => $brightnessPct,
            'color_temp_kelvin' => $colorTempKelvin,
            'effect' => $effect,
            'flash' => $flash,
            'profile' => $profile,
            'rgb_color' => $rgbColor,
            'transition' => $transition,
            'white' => $white,
        ], $target);
    }
}
