<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\Entity\EntityId;
use Stewart\Contracts\HaContext;

/**
 * The `light` entities.
 */
final class LightEntities
{
    /** First Floor */
    public LightEntity $_1stFloor {
        get => new LightEntity($this->ha, new EntityId('light.1st_floor'));
    }

    /** Hall */
    public LightEntity $hall {
        get => new LightEntity($this->ha, new EntityId('light.hall'));
    }

    /** Porch 2 */
    public LightEntity $porch2 {
        get => new LightEntity($this->ha, new EntityId('light.porch2'));
    }

    /** Porch Two */
    public LightEntity $porch22 {
        get => new LightEntity($this->ha, new EntityId('light.porch_2'));
    }

    public function __construct(private readonly HaContext $ha)
    {
    }
}
