<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\Entity\Entity;
use Stewart\Contracts\Entity\EntityId;
use Stewart\Contracts\Entity\TypedEntity;
use Stewart\Contracts\Exception\HistoryException;
use Stewart\Contracts\Exception\IdentifierException;
use Stewart\Contracts\Exception\StateException;
use Stewart\Contracts\HaContext;
use Stewart\Contracts\History\EntityStateHistory;
use Stewart\Contracts\History\HistoryQuery;
use Stewart\Contracts\Service\ServiceTarget;
use Stewart\Contracts\StateChangeStream;

/**
 * One `light` entity.
 */
final readonly class LightEntity implements TypedEntity
{
    private const array GENERATED_ENTITY_IDS = [
        'light.1st_floor' => true,
        'light.hall' => true,
        'light.porch2' => true,
        'light.porch_2' => true,
    ];

    private Entity $entity;

    /**
     * @throws IdentifierException
     */
    public function __construct(
        HaContext $ha,
        public EntityId $id,
    ) {
        if (!self::isGeneratedEntityId($id)) {
            throw IdentifierException::entityNotGenerated($id->value, self::getDomain());
        }

        $this->entity = $ha->getEntity($id);
    }

    public static function getDomain(): string
    {
        return 'light';
    }

    public static function isGeneratedEntityId(EntityId $id): bool
    {
        return isset(self::GENERATED_ENTITY_IDS[$id->value]);
    }

    public function getState(): ?LightState
    {
        return LightState::fromNullableState($this->entity->getState());
    }

    /**
     * @throws StateException
     */
    public function requireState(): LightState
    {
        return new LightState($this->entity->requireState());
    }

    public function watchStateChanges(): StateChangeStream
    {
        return $this->entity->watchStateChanges();
    }

    /**
     * @throws HistoryException
     */
    public function getHistory(HistoryQuery $query): EntityStateHistory
    {
        return $this->entity->getHistory($query);
    }

    /**
     * @return array<string, mixed>
     */
    public function listAttributes(): array
    {
        $state = $this->entity->getState();

        return $state === null ? [] : $state->attributes;
    }

    public function getEntity(): Entity
    {
        return $this->entity;
    }

    public function toServiceTarget(): ServiceTarget
    {
        return $this->entity->toServiceTarget();
    }

    /**
     * Set state
     *
     * Writes a state straight onto a light, bypassing its integration.
     *
     * @param string|int|float $value Value. The state to write
     */
    public function state(string|int|float $value): void
    {
        $this->entity->callService('state', [
            'value' => $value,
        ]);
    }

    /**
     * Turn off
     *
     * Turns off one or more lights.
     *
     * @param int|float|null $transition Transition. Duration it takes to get to the next state. 0 to 300 seconds
     */
    public function turnOff(int|float|null $transition = null): void
    {
        $this->entity->callService('turn_off', [
            'transition' => $transition,
        ]);
    }

    /**
     * Turn on
     *
     * Turns on one or more lights and adjusts their properties, even when they are on already.
     *
     * @param int|float|null $brightnessPct Brightness. Percentage of full brightness. 0 to 100 %
     * @param int|float|null $colorTempKelvin Color temperature. Colour temperature in Kelvin. 2000 to 6500
     * @param string|int|float|null $effect Effect. Light effect
     * @param 'long'|'short'|null $flash Flash. Tell the light to flash
     * @param mixed $profile Profile. A light profile, if the integration offers any
     * @param array{int, int, int}|null $rgbColor RGB color. The color in RGB format
     * @param int|float|null $transition Transition. Duration it takes to get to the next state. 0 to 300 seconds
     * @param true|null $white White. Set the light to white mode
     */
    public function turnOn(
        int|float|null $brightnessPct = null,
        int|float|null $colorTempKelvin = null,
        string|int|float|null $effect = null,
        ?string $flash = null,
        mixed $profile = null,
        ?array $rgbColor = null,
        int|float|null $transition = null,
        ?bool $white = null,
    ): void {
        $this->entity->callService('turn_on', [
            'brightness_pct' => $brightnessPct,
            'color_temp_kelvin' => $colorTempKelvin,
            'effect' => $effect,
            'flash' => $flash,
            'profile' => $profile,
            'rgb_color' => $rgbColor,
            'transition' => $transition,
            'white' => $white,
        ]);
    }
}
