<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\Entity\EntityId;
use Stewart\Contracts\Exception\IdentifierException;
use Stewart\Contracts\HaContext;

/**
 * The `light` entities.
 */
final readonly class LightEntities
{
    public function __construct(private HaContext $ha)
    {
    }

    /**
     * @throws IdentifierException
     */
    public function getEntity(string|EntityId $id): LightEntity
    {
        return new LightEntity($this->ha, EntityId::fromStringOrId($id));
    }
}
