<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\Generated\Manifest as ManifestContract;

/**
 * What `stewart generate` saw.
 */
final class Manifest implements ManifestContract
{
    public const int FORMAT_VERSION = 4;

    private function __construct()
    {
    }

    /**
     * @return list<string>
     */
    public static function listEntityIds(): array
    {
        return [
            'binary_sensor.hall_motion',
            'input_number.target_temperature',
            'light.1st_floor',
            'light.hall',
            'light.porch2',
            'light.porch_2',
            'sensor.broken_probe',
            'sensor.hall_humidity',
            'sensor.hall_temperature',
            'switch.pump',
        ];
    }

    /**
     * @return list<string>
     */
    public static function listIgnoredEntityIds(): array
    {
        return ['light.attic', 'light.cellar', 'light.debug_strip'];
    }
}
