<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\HaContext;
use Stewart\Contracts\State\EventContext;

/**
 * The `notify` services.
 */
final readonly class NotifyServices
{
    public function __construct(private HaContext $ha)
    {
    }

    /**
     * Send a notification via mobile_app_phone
     *
     * Sends a notification message through the mobile_app_phone integration.
     *
     * @param string|int|float $message Message. Body of the notification
     * @param array<array-key, mixed>|null $data Data. Extended information for the notification
     * @param list<string|int|float>|null $target Target. Who receives it
     * @param string|int|float|null $title Title. Title of the notification
     */
    public function mobileAppPhone(
        string|int|float $message,
        ?array $data = null,
        ?array $target = null,
        string|int|float|null $title = null,
    ): EventContext {
        return $this->ha->callService('notify', 'mobile_app_phone', [
            'message' => $message,
            'data' => $data,
            'target' => $target,
            'title' => $title,
        ]);
    }
}
