<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\Entity\EntityId;
use Stewart\Contracts\HaContext;

/**
 * The `sensor` entities.
 */
final class SensorEntities
{
    /** Broken Probe */
    public SensorEntity $brokenProbe {
        get => new SensorEntity($this->ha, new EntityId('sensor.broken_probe'));
    }

    /** Hall Humidity */
    public SensorEntity $roomHumidity {
        get => new SensorEntity($this->ha, new EntityId('sensor.hall_humidity'));
    }

    /** Hall Temperature */
    public SensorEntity $hallTemperature {
        get => new SensorEntity($this->ha, new EntityId('sensor.hall_temperature'));
    }

    public function __construct(private readonly HaContext $ha)
    {
    }
}
