<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\State\EntityState;

/**
 * What a `sensor` entity is doing.
 */
final readonly class SensorState
{
    public string $value;

    public function __construct(public EntityState $raw)
    {
        $this->value = $raw->state;
    }

    public static function fromNullableState(?EntityState $raw): ?self
    {
        return $raw === null ? null : new self($raw);
    }

    public function getStateAsFloat(): ?float
    {
        return $this->raw->getStateAsFloat();
    }

    public function isUnavailable(): bool
    {
        return $this->raw->isUnavailable();
    }

    public function getFriendlyName(): string
    {
        return $this->raw->getFriendlyName();
    }

    public function getBattery(): ?float
    {
        return $this->raw->getFloatAttribute('battery');
    }

    public function getLastReset(): ?string
    {
        return $this->raw->getStringAttribute('last_reset');
    }

    /**
     * @return array<array-key, mixed>|null
     */
    public function getOptions(): ?array
    {
        return $this->raw->getArrayAttribute('options');
    }

    public function getUnitOfMeasurement(): ?string
    {
        return $this->raw->getStringAttribute('unit_of_measurement');
    }
}
