<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\HaContext;

/**
 * Every service Home Assistant offers, by domain.
 */
final class Services
{
    /** Services in the `homeassistant` domain. */
    public HomeassistantServices $homeassistant {
        get => new HomeassistantServices($this->ha);
    }

    /** Services in the `light` domain. */
    public LightServices $light {
        get => new LightServices($this->ha);
    }

    /** Services in the `notify` domain. */
    public NotifyServices $notify {
        get => new NotifyServices($this->ha);
    }

    /** Services in the `switch` domain. */
    public SwitchServices $switch {
        get => new SwitchServices($this->ha);
    }

    /** Services in the `weather` domain. */
    public WeatherServices $weather {
        get => new WeatherServices($this->ha);
    }

    public function __construct(private readonly HaContext $ha)
    {
    }
}
