<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\Entity\Entity;
use Stewart\Contracts\Entity\EntityId;
use Stewart\Contracts\Entity\TypedEntity;
use Stewart\Contracts\Exception\IdentifierException;
use Stewart\Contracts\Exception\StateException;
use Stewart\Contracts\HaContext;
use Stewart\Contracts\Service\ServiceTarget;
use Stewart\Contracts\StateChangeStream;

/**
 * One `switch` entity.
 */
final readonly class SwitchEntity implements TypedEntity
{
    private const array GENERATED_ENTITY_IDS = ['switch.pump' => true];

    private Entity $entity;

    /**
     * @throws IdentifierException
     */
    public function __construct(
        HaContext $ha,
        public EntityId $id,
    ) {
        if (!self::isGeneratedEntityId($id)) {
            throw IdentifierException::entityNotGenerated($id->value, self::getDomain());
        }

        $this->entity = $ha->getEntity($id);
    }

    public static function getDomain(): string
    {
        return 'switch';
    }

    public static function isGeneratedEntityId(EntityId $id): bool
    {
        return isset(self::GENERATED_ENTITY_IDS[$id->value]);
    }

    public function getState(): ?SwitchState
    {
        return SwitchState::fromNullableState($this->entity->getState());
    }

    /**
     * @throws StateException
     */
    public function requireState(): SwitchState
    {
        return new SwitchState($this->entity->requireState());
    }

    public function watchStateChanges(): StateChangeStream
    {
        return $this->entity->watchStateChanges();
    }

    /**
     * @return array<string, mixed>
     */
    public function listAttributes(): array
    {
        $state = $this->entity->getState();

        return $state === null ? [] : $state->attributes;
    }

    public function getEntity(): Entity
    {
        return $this->entity;
    }

    public function toServiceTarget(): ServiceTarget
    {
        return $this->entity->toServiceTarget();
    }

    /**
     * Turn on
     *
     * Turns a switch on.
     */
    public function turnOn(): void
    {
        $this->entity->callService('turn_on');
    }
}
