<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\State\EntityState;

/**
 * What a `switch` entity is doing.
 */
final readonly class SwitchState
{
    public string $value;

    public function __construct(public EntityState $raw)
    {
        $this->value = $raw->state;
    }

    public static function fromNullableState(?EntityState $raw): ?self
    {
        return $raw === null ? null : new self($raw);
    }

    public function isOn(): bool
    {
        return $this->value === 'on';
    }

    public function isOff(): bool
    {
        return $this->value === 'off';
    }

    public function isUnavailable(): bool
    {
        return $this->raw->isUnavailable();
    }

    public function getFriendlyName(): string
    {
        return $this->raw->getFriendlyName();
    }
}
