<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\Entity\EntityId;
use Stewart\Contracts\HaContext;

/**
 * The `switch` entities.
 */
final class SwitchEntities
{
    /** Pump */
    public SwitchEntity $pump {
        get => new SwitchEntity($this->ha, new EntityId('switch.pump'));
    }

    public function __construct(private readonly HaContext $ha)
    {
    }
}
