<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\HaContext;
use Stewart\Contracts\Service\ServiceTargetSource;

/**
 * The `switch` services.
 */
final readonly class SwitchServices
{
    public function __construct(private HaContext $ha)
    {
    }

    /**
     * Turn on
     *
     * Turns a switch on.
     */
    public function turnOn(ServiceTargetSource $target): void
    {
        $this->ha->callService('switch', 'turn_on', [], $target);
    }
}
