<?php

declare(strict_types=1);

/**
 * @generated by `stewart generate`.
 *
 * Do not edit: run `make generate` instead.
 */

namespace Stewart\Codegen\Tests\Fixtures\Expected;

use Stewart\Contracts\HaContext;
use Stewart\Contracts\Service\ServiceResponse;
use Stewart\Contracts\Service\ServiceTargetSource;

/**
 * The `weather` services.
 */
final readonly class WeatherServices
{
    public function __construct(private HaContext $ha)
    {
    }

    /**
     * Get forecasts
     *
     * Retrieves the forecast from selected weather services.
     *
     * @param 'daily'|'hourly' $type Forecast type. The scope of the weather forecast
     */
    public function getForecasts(ServiceTargetSource $target, string $type): ServiceResponse
    {
        return $this->ha->callServiceForResponse('weather', 'get_forecasts', [
            'type' => $type,
        ], $target);
    }
}
